# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 158b10beb578757050a4e3663f2877a932081e67a18fbde343f4bd8e169cad882b56d7ccd81f1bf055c27d1ea7500e88e0c1a47836638aa6167a8c488e9265d3

test:
  secret_key_base: 6131941599d825240fd775fdf98fff444280a67fc245724e4ad4cd180535708a066d12e588d3f75a8deb74b943bcf6753393ab667b47e1d38a940b5324211c87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
